-- Category-agnostic orders (plan: Stage 1 amendment, 2026-09-15).
--
-- `bookings` assumed one kind of job: one time block, a fixed price known in
-- advance, instant confirmation, no service address. It is replaced by
-- `orders` (what and who) and `appointments` (when), plus `quotes` and
-- `order_events`. How a service is delivered and sold becomes four settings
-- on business_services, with defaults on canonical_services; the engine and
-- agent read those, never the category id.
--
-- Generated by drizzle-kit, then edited by hand in two places: the
-- steps/default_steps backfills (a NOT NULL column can't be added to a
-- populated table without one), and the double-booking guard at the end.

CREATE TABLE "appointments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"order_id" uuid NOT NULL,
	"business_id" uuid NOT NULL,
	"kind" text NOT NULL,
	"resource_index" integer DEFAULT 0 NOT NULL,
	"scheduled_at" timestamp with time zone NOT NULL,
	"duration_min" integer NOT NULL,
	"buffer_min" integer DEFAULT 0 NOT NULL,
	"ends_at" timestamp with time zone DEFAULT now() NOT NULL,
	"status" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "appointments_kind_check" CHECK ("appointments"."kind" IN ('visit', 'pickup', 'delivery', 'job')),
	CONSTRAINT "appointments_status_check" CHECK ("appointments"."status" IN ('held', 'confirmed', 'completed', 'cancelled', 'no_show')),
	CONSTRAINT "appointments_resource_index_check" CHECK ("appointments"."resource_index" >= 0)
);
--> statement-breakpoint
CREATE TABLE "order_events" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"order_id" uuid NOT NULL,
	"actor" text NOT NULL,
	"type" text NOT NULL,
	"payload" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"delivered_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "order_events_actor_check" CHECK ("order_events"."actor" IN ('user', 'business', 'system'))
);
--> statement-breakpoint
CREATE TABLE "orders" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"search_id" uuid,
	"business_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"business_service_id" uuid NOT NULL,
	"status" text NOT NULL,
	"service_address" text,
	"service_lat" numeric(9, 6),
	"service_lng" numeric(9, 6),
	"quantity" numeric(10, 2),
	"details" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"price_aed" numeric(10, 2),
	"final_price_aed" numeric(10, 2),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "orders_status_check" CHECK ("orders"."status" IN ('requested', 'quoted', 'confirmed', 'in_progress', 'completed', 'declined', 'cancelled_by_user', 'cancelled_by_business', 'no_show')),
	CONSTRAINT "orders_service_location_check" CHECK (("orders"."service_lat" IS NULL) = ("orders"."service_lng" IS NULL))
);
--> statement-breakpoint
CREATE TABLE "quotes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"order_id" uuid NOT NULL,
	"amount_aed" numeric(10, 2) NOT NULL,
	"est_duration_min" integer NOT NULL,
	"line_items" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"valid_until" timestamp with time zone NOT NULL,
	"status" text DEFAULT 'sent' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "quotes_status_check" CHECK ("quotes"."status" IN ('sent', 'accepted', 'declined', 'expired'))
);
--> statement-breakpoint
ALTER TABLE "bookings" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP TABLE "bookings" CASCADE;--> statement-breakpoint
ALTER TABLE "business_services" DROP CONSTRAINT "business_services_business_service_key";--> statement-breakpoint
ALTER TABLE "business_services" ALTER COLUMN "price_aed" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "search_options" ALTER COLUMN "price_aed" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "business_services" ADD COLUMN "location_mode" text DEFAULT 'at_business' NOT NULL;--> statement-breakpoint
ALTER TABLE "business_services" ADD COLUMN "pricing_mode" text DEFAULT 'fixed' NOT NULL;--> statement-breakpoint
ALTER TABLE "business_services" ADD COLUMN "unit_label" text;--> statement-breakpoint
ALTER TABLE "business_services" ADD COLUMN "confirmation" text DEFAULT 'instant' NOT NULL;--> statement-breakpoint
ALTER TABLE "business_services" ADD COLUMN "steps" jsonb;--> statement-breakpoint
-- Every existing service is a single job of its old duration_min.
UPDATE "business_services" SET "steps" = jsonb_build_array(jsonb_build_object('kind', 'job', 'duration_min', "duration_min"));--> statement-breakpoint
ALTER TABLE "business_services" ALTER COLUMN "steps" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "canonical_services" ADD COLUMN "default_location_mode" text DEFAULT 'at_business' NOT NULL;--> statement-breakpoint
ALTER TABLE "canonical_services" ADD COLUMN "default_pricing_mode" text DEFAULT 'fixed' NOT NULL;--> statement-breakpoint
ALTER TABLE "canonical_services" ADD COLUMN "default_unit_label" text;--> statement-breakpoint
ALTER TABLE "canonical_services" ADD COLUMN "default_confirmation" text DEFAULT 'instant' NOT NULL;--> statement-breakpoint
ALTER TABLE "canonical_services" ADD COLUMN "default_steps" jsonb;--> statement-breakpoint
UPDATE "canonical_services" SET "default_steps" = jsonb_build_array(jsonb_build_object('kind', 'job', 'duration_min', "typical_duration_min"));--> statement-breakpoint
ALTER TABLE "canonical_services" ALTER COLUMN "default_steps" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "searches" ADD COLUMN "address" text;--> statement-breakpoint
ALTER TABLE "appointments" ADD CONSTRAINT "appointments_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "appointments" ADD CONSTRAINT "appointments_business_id_businesses_id_fk" FOREIGN KEY ("business_id") REFERENCES "public"."businesses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order_events" ADD CONSTRAINT "order_events_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_search_id_searches_id_fk" FOREIGN KEY ("search_id") REFERENCES "public"."searches"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_business_id_businesses_id_fk" FOREIGN KEY ("business_id") REFERENCES "public"."businesses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_business_service_id_business_services_id_fk" FOREIGN KEY ("business_service_id") REFERENCES "public"."business_services"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "quotes" ADD CONSTRAINT "quotes_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "appointments_business_scheduled_idx" ON "appointments" USING btree ("business_id","scheduled_at");--> statement-breakpoint
CREATE INDEX "appointments_order_idx" ON "appointments" USING btree ("order_id");--> statement-breakpoint
CREATE INDEX "order_events_order_created_idx" ON "order_events" USING btree ("order_id","created_at");--> statement-breakpoint
CREATE INDEX "order_events_undelivered_idx" ON "order_events" USING btree ("created_at") WHERE "order_events"."delivered_at" IS NULL;--> statement-breakpoint
CREATE INDEX "orders_business_created_idx" ON "orders" USING btree ("business_id","created_at");--> statement-breakpoint
CREATE INDEX "orders_user_created_idx" ON "orders" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE INDEX "quotes_order_idx" ON "quotes" USING btree ("order_id");--> statement-breakpoint
ALTER TABLE "business_services" DROP COLUMN "duration_min";--> statement-breakpoint
ALTER TABLE "canonical_services" DROP COLUMN "typical_duration_min";--> statement-breakpoint
ALTER TABLE "business_services" ADD CONSTRAINT "business_services_business_service_location_key" UNIQUE("business_id","canonical_service_id","location_mode");--> statement-breakpoint
ALTER TABLE "business_services" ADD CONSTRAINT "business_services_location_mode_check" CHECK ("business_services"."location_mode" IN ('at_business', 'at_customer', 'pickup_delivery'));--> statement-breakpoint
ALTER TABLE "business_services" ADD CONSTRAINT "business_services_pricing_mode_check" CHECK ("business_services"."pricing_mode" IN ('fixed', 'from', 'per_unit', 'quote'));--> statement-breakpoint
ALTER TABLE "business_services" ADD CONSTRAINT "business_services_confirmation_check" CHECK ("business_services"."confirmation" IN ('instant', 'request'));--> statement-breakpoint
ALTER TABLE "business_services" ADD CONSTRAINT "business_services_price_check" CHECK ("business_services"."price_aed" IS NOT NULL OR "business_services"."pricing_mode" = 'quote');--> statement-breakpoint
ALTER TABLE "business_services" ADD CONSTRAINT "business_services_unit_label_check" CHECK (("business_services"."pricing_mode" = 'per_unit') = ("business_services"."unit_label" IS NOT NULL));--> statement-breakpoint
ALTER TABLE "canonical_services" ADD CONSTRAINT "canonical_services_location_mode_check" CHECK ("canonical_services"."default_location_mode" IN ('at_business', 'at_customer', 'pickup_delivery'));--> statement-breakpoint
ALTER TABLE "canonical_services" ADD CONSTRAINT "canonical_services_pricing_mode_check" CHECK ("canonical_services"."default_pricing_mode" IN ('fixed', 'from', 'per_unit', 'quote'));--> statement-breakpoint
ALTER TABLE "canonical_services" ADD CONSTRAINT "canonical_services_confirmation_check" CHECK ("canonical_services"."default_confirmation" IN ('instant', 'request'));--> statement-breakpoint
ALTER TABLE "canonical_services" ADD CONSTRAINT "canonical_services_unit_label_check" CHECK (("canonical_services"."default_pricing_mode" = 'per_unit') = ("canonical_services"."default_unit_label" IS NOT NULL));--> statement-breakpoint

-- The double-booking guard moves from bookings (dropped above) to
-- appointments. 0001_booking_guard.sql explains why it looks like this — a
-- trigger-filled ends_at, btree_gist, a half-open range. Only the table
-- changes, plus `held` in the partial index: a requested order's appointment
-- occupies its slot until the business decides, so the business never
-- confirms a time that has gone. Declining cancels it and frees the slot.
ALTER FUNCTION set_booking_ends_at() RENAME TO set_appointment_ends_at;--> statement-breakpoint
CREATE TRIGGER appointments_ends_at
BEFORE INSERT OR UPDATE OF scheduled_at, duration_min, buffer_min ON appointments
FOR EACH ROW EXECUTE FUNCTION set_appointment_ends_at();--> statement-breakpoint
ALTER TABLE appointments ADD CONSTRAINT no_double_booking
EXCLUDE USING gist (
  business_id    WITH =,
  resource_index WITH =,
  tstzrange(scheduled_at, ends_at) WITH &&
) WHERE (status IN ('held','confirmed','completed'));